// Generated by https://quicktype.io

export interface Provedores {
    provedores: Provedor[];
}

export interface Provedor {
    id:                     string;
    nombre:                 string;
    alias:                  null | string;
    RFC:                    string;
    telefono:               string;
    movil:                  null;
    correo:                 string;
    sitio_web:              null;
    etiquetas:              null;
    condicionesComerciales: CondicionesComerciales[];
    condicionesPago:        CondicionesPago[];
    tarifas:                Tarifa[];
    recordatorio_recibo:    boolean;
    notas:                  string;
    tipoDePersona:          TipoDePersona;
    direcciones:            Direccion[];
    cuentasBancarias:       CuentaBancaria[];
}


export enum CondicionesPago {
    The15Dias = "15 DIAS",
    The21Dias = "21 DIAS",
    The45Dias = "45 DIAS",
}


export interface CuentaBancaria {
    id:            string;
    numero_cuenta: string;
    banco:         string;
    tipo:          string;
    CLABE:         string;
}


export interface Direccion {
    id:     string;
    calle:  string;
    estado: string;
    ciudad: string;
    CP:     string;
}



export enum Tarifa {
    MXN = "MXN",
}

export enum CondicionesComerciales {
    CONTADO = "CONTADO",
    CREDITO = "CREDITO"
};


export enum TipoDePersona {
    MORAL = "MORAL",
    FISICA = "FISICA"
};

export enum CondicionesPago {
    PAGO_INMEDIATO = "PAGO_INMEDIATO",
    "15 DIAS" = "15 DIAS",
    "21 DIAS" = "21 DIAS",
    "30 DIAS" = "30 DIAS",
    "45 DIAS" = "45 DIAS",
    "FIN DE MES" = "FIN DE MES"
};